### ISSUE TITLE
slinky menu doesn't work on some phone browsers

### ISSUE THREAD

**Issue by boulmerhras** [alizahid/slinky#31] opened 2018-03-04 00:01 UTC
hello,
i have added slinky menu to my website, it works perfectly in all browsers except some phone browsers, like samsung browser, or iphone default browser, 
Any suggestion?

**Comment by ScoutsOut** [comment] 2018-06-11 22:18
@boulmerhras - I'm not a maintainer but it would be helpful to the community to provide greater details regarding the issues you ran into.

What exactly were the issues? Were they performance-based issues? Presentation (CSS) layer issues?
JS issues?

Thanks again. Provide some details and I'm sure someone will comment. @alizahid

**Comment by alizahid** [comment] 2019-07-14 08:05
Yeah, really need more details on this. Steps to reproduce, etc.

Since this issue is very old, I'm closing it. You can create a new one if you're still seeing this.

**Closed by alizahid** 2019-07-14 08:05 UTC
